spring:
  application:
    name: SkincareBookingSystem
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=SkincareBookingSystem_db;encrypt=false
    username: MSI
    password: 1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9090

jwt:
  key: zvU8wxF4V0Ev2/LJb0HqDFs9ZAdX5PLIHtLqkiwlZvRB+9BJ24QDa+dhzErrUzFF
  issuer: Skincare-Platform
  audience: Skincare-Platform
  access-token:
    expire-time: 30
  refresh-token:
    expire-time: 60

app:
  emailsetting:
    sender: MAdminBookingSystem@gmail.com
    login-password: AdminBookingSystem@123
    password: $2a$10$oCMfEPHRmV8/o8kkBwfXXu2UZpqrS7lrQpyOd1LsauXRhIxP9VrXa
openai:
  api-url: https://gpt-proxy-api.fly.dev/v1/chat/completions
  api-key: dummy-key